#!/usr/bin/env php
<?php
error_reporting(E_ALL & ~E_DEPRECATED & ~E_NOTICE);

if (version_compare("8.1", phpversion()) == 1) {
	echo 'Not support PHP < 8.1';
	exit;
}

if (!is_readable('vendor/autoload.php')) {
	echo 'You should install composer from https://getcomposer.org/ and run ``composer install`` firstly.';
	exit;
}

define('ROOT_PATH', dirname(__FILE__));

require 'vendor/autoload.php';
require './validator/bootstrap.php';